sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t practicaljava/docker-react -f Dockerfile.dev .

#only to run our test we are building from Dockerfile.dev
script:
  - docker run -e CI=true practicaljava/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'docker-react'
  env: 'dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-west-2-987484768899'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY