sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t practicaljava/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true practicaljava/docker-react npm run test